### ISSUE TITLE
Bug affichage météo

### ISSUE THREAD

**Issue by geekoun** [GladysAssistant/gladys-forecast#4]
Voici le bug dans paramètre=>paramètre (console.log()): 

![capture d ecran 2019-03-02 a 11 35 10](https://user-images.githubusercontent.com/4254819/53680709-63212180-3cdf-11e9-8e25-01032b6e5946.png)

Quand je souhaite supprimer la première clé : FORECAST_API_KEY 

![capture d ecran 2019-03-02 a 11 38 40](https://user-images.githubusercontent.com/4254819/53680753-ffe3bf00-3cdf-11e9-9d02-eb3c227467e9.png)

Les autres suppressions fonctionnent !

Autre problème, je suis en https://gladys.local/, le module météo est installé mais rien n'y fait....

Voici le log d'erreur quand je suis sur le tableau de bord (accueil) : 
```
Error: No weather provider available
0|gladys   |     at getWeatherProvider (/home/pi/gladys/api/core/weather/weather.get.js:72:27)
0|gladys   |     at Object.get (/home/pi/gladys/api/core/weather/weather.get.js:53:10)
0|gladys   |     at Object.get (/home/pi/gladys/api/controllers/WeatherController.js:24:8)
0|gladys   |     at wrapper (/home/pi/gladys/node_modules/@sailshq/lodash/lib/index.js:3275:19)
0|gladys   |     at routeTargetFnWrapper (/home/pi/gladys/node_modules/sails/lib/router/bind.js:181:5)
0|gladys   |     at callbacks (/home/pi/gladys/node_modules/@sailshq/express/lib/router/index.js:164:37)
0|gladys   |     at param (/home/pi/gladys/node_modules/@sailshq/express/lib/router/index.js:138:11)
0|gladys   |     at pass (/home/pi/gladys/node_modules/@sailshq/express/lib/router/index.js:145:5)
0|gladys   |     at nextRoute (/home/pi/gladys/node_modules/@sailshq/express/lib/router/index.js:100:7)
0|gladys   |     at callbacks (/home/pi/gladys/node_modules/@sailshq/express/lib/router/index.js:167:11)
0|gladys   |     at module.exports (/home/pi/gladys/api/policies/checkToken.js:4:12)
0|gladys   |     at routeTargetFnWrapper (/home/pi/gladys/node_modules/sails/lib/router/bind.js:181:5)
0|gladys   |     at callbacks (/home/pi/gladys/node_modules/@sailshq/express/lib/router/index.js:164:37)
0|gladys   |     at param (/home/pi/gladys/node_modules/@sailshq/express/lib/router/index.js:138:11)
0|gladys   |     at pass (/home/pi/gladys/node_modules/@sailshq/express/lib/router/index.js:145:5)
0|gladys   |     at nextRoute (/home/pi/gladys/node_modules/@sailshq/express/lib/router/index.js:100:7)
0|gladys   |     at callbacks (/home/pi/gladys/node_modules/@sailshq/express/lib/router/index.js:167:11)
0|gladys   |     at _sendHeaders (/home/pi/gladys/node_modules/sails/lib/hooks/cors/to-prepare-send-headers.js:91:7)
0|gladys   |     at routeTargetFnWrapper (/home/pi/gladys/node_modules/sails/lib/router/bind.js:181:5)
0|gladys   |     at callbacks (/home/pi/gladys/node_modules/@sailshq/express/lib/router/index.js:164:37)
0|gladys   |     at param (/home/pi/gladys/node_modules/@sailshq/express/lib/router/index.js:138:11)
0|gladys   |     at pass (/home/pi/gladys/node_modules/@sailshq/express/lib/router/index.js:145:5)
```

**Comment by Pierre-Gilles** [comment]
Hello! Pour le support, le mieux est de venir sur la communauté =>

https://community.gladysassistant.com/

On utilise GitHub plus pour tracker les issues, c'est assez compliqué de l'utiliser pour aider à l'installation :)
